version: 0.2

phases:
  install:
    commands:
      - echo install step...
      - AWS_CRED=`curl ${cred_url}$${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI}`
      - AWS_ACCESS_KEY_ID=`echo $${AWS_CRED} | jq -r .AccessKeyId`
      - AWS_SECRET_ACCESS_KEY=`echo $${AWS_CRED} | jq -r .SecretAccessKey`
      - AWS_SESSION_TOKEN=`echo $${AWS_CRED} | jq -r .Token`
      - DEPLOY_DOMAIN=${deploy_domain}
      - DEPLOY_SUB_DOMAIN=${deploy_sub_domain}
      - NEXT_PUBLIC_API_URL=${next_public_api_url}
  pre_build:
    commands:
      - echo pre build
      - cd ${app_dir}
      - wc=`aws s3 ls s3://${bucket}${bucket_dir}${node_modules}.tar.gz | wc -c`
      - if [ "$${wc}" -gt 0 ]; then echo "loading ${node_modules} ..."; aws s3 cp s3://${bucket}${bucket_dir}${node_modules}.tar.gz - | gzip -d | tar xf -; fi
      - wc=`aws s3 ls s3://${bucket}${bucket_dir}${next}.tar.gz | wc -c`
      - if [ "$${wc}" -gt 0 ]; then echo "loading ${next} ..."; aws s3 cp s3://${bucket}${bucket_dir}${next}.tar.gz - | gzip -d | tar xf -; fi
      - wc=`aws s3 ls s3://${bucket}${bucket_dir}${sls}.tar.gz | wc -c`
      - if [ "$${wc}" -gt 0 ]; then echo "loading ${sls} ..."; aws s3 cp s3://${bucket}${bucket_dir}${sls}.tar.gz - | gzip -d | tar xf -; fi
      - wc=`aws s3 ls s3://${bucket}${bucket_dir}${sls_next}.tar.gz | wc -c`
      - if [ "$${wc}" -gt 0 ]; then echo "loading ${sls_next} ..."; aws s3 cp s3://${bucket}${bucket_dir}${sls_next}.tar.gz - | gzip -d | tar xf -; fi
      - cd -
  build:
    commands:
      - echo build...
      - docker-compose -f ${docker_compose_file} run deploy /bin/bash -c "yarn && NODE_ENV=production yarn next build && NODE_ENV=production components-v1"
  post_build:
    commands:
      - echo post build
      - cd ${app_dir}
      - tar cf - ${sls_next} | gzip --best | aws s3 cp - s3://${bucket}${bucket_dir}${sls_next}.tar.gz
      - tar cf - ${sls} | gzip --best | aws s3 cp - s3://${bucket}${bucket_dir}${sls}.tar.gz
      - tar cf - ${next} | gzip --best | aws s3 cp - s3://${bucket}${bucket_dir}${next}.tar.gz
      - tar cf - ${node_modules} | gzip --best | aws s3 cp - s3://${bucket}${bucket_dir}${node_modules}.tar.gz
      - cd -
